// Generated by CoffeeScript 1.9.0
(function() {
  var anpan, btn, kuji, result, unmei;
  btn = document.getElementById("omikuji");
  result = document.getElementById("unmei");
  anpan = document.getElementById("anpan");
  unmei = function(txt, hiita) {
    result.innerHTML = txt;
    return (document.getElementById("anpan")).src = "img/anpan-0" + hiita + ".png";
  };
  kuji = function() {
    var hiita;
    hiita = Math.floor(Math.random() * 4);
    switch (hiita) {
      case 0:
        return unmei("大吉:浮かれてんじゃねーぞ", hiita);
      case 1:
        return unmei("中吉:まあまあだな", hiita);
      case 2:
        return unmei("吉:普通だな", hiita);
      case 3:
        return unmei("凶:お前はもう死んでいる", hiita);
    }
  };
  return btn.addEventListener("click", kuji, false);
})();
