// Generated by CoffeeScript 1.9.0
(function() {
  var btn, kuji, result, unmei;
  btn = document.getElementById("omikuji");
  result = document.getElementById("unmei");
  unmei = function(txt) {
    return result.innerHTML = txt;
  };
  kuji = function() {
    console.log(Math.floor(Math.random() * 4));
    switch (Math.floor(Math.random() * 4)) {
      case 0:
        return unmei("大吉:浮かれてんじゃねーぞ");
      case 1:
        return unmei("中吉:まあまあだな");
      case 2:
        return unmei("吉:普通だな");
      case 3:
        return unmei("凶:お前はもう死んでいる");
    }
  };
  return btn.addEventListener("click", kuji, false);
})();
